### ISSUE TITLE
Community Guidelines Missing

### ISSUE THREAD

**Issue by CameronDevine** [lbr-stack/lbr_stack_doc#24]
As part of the JOSS review (openjournals/joss-reviews#6138) there must be clearly stated community guidelines, and I haven't been able to find any. I think these guidelines could either be added to your readthedocs.io documentation, or included in each repository. For your reference, the following is required:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by CameronDevine** [comment]
Just as a reminder, the community guidelines should be included in each repository, or added to the documentation. Let me know if you would like me to open issues in the other repositories.

**Comment by mhubii** [comment]
no worries, will amend the changes, thank you for the feedback

**Comment by mhubii** [comment]
contributing:

| Repository | CONTRIBUTING.md | CODE_OF_CONDUCT.md | 
| ---------------- | -----------------------------| -- |
|  `lbr_stack_doc`  |  [ ] [link]()  | [x] [link](https://github.com/lbr-stack/lbr_stack_doc/blob/main/CODE_OF_CONDUCT.md)|
|  `fri`  | [ ] [link]()   | [ ] [link]() |
|  `pyFRI`  | [x] [link](https://github.com/lbr-stack/pyFRI/blob/main/.github/CONTRIBUTING.md)    | [x] [link](https://github.com/lbr-stack/pyFRI/blob/main/CODE_OF_CONDUCT.md)| 
|  `lbr_fri_ros2_stack`  | [x] [link](https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/humble/.github/CONTRIBUTING.md)    | [x] [link](https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/humble/CODE_OF_CONDUCT.md) |
|  `lbr_fri_idl`  | [ ] [link]()    | [ ] [link]() |
