### ISSUE TITLE
JOSS Paper: unclear limitations in statement of need

### ISSUE THREAD

**Issue by dmronga** [lbr-stack/lbr_stack_doc#26]
Lines 43 and 44 (maintainability) are a bit unclear, can you explain this in more detail?

**Comment by dmronga** [comment]
openjournals/joss-reviews#6138

**Comment by mhubii** [comment]
thank you for the feedback, this was indeed quite unclear. This should now be fixed, I'll re-generate the PDF. Please re-open if anything remains unclear
