### ISSUE TITLE
Missing target OS and ROS2 version in Installation instructions

### ISSUE THREAD

**Issue by dmronga** [lbr-stack/lbr_stack_doc#27]
In the installation instructions found [here](https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/humble/README.md), it would be good to state clearly what are the supported OS, ROS2 versions and FRI versions.

Also the requirements are missing, e.g. installed ros2-humble-desktop-full

**Comment by dmronga** [comment]
openjournals/joss-reviews#6138

**Comment by mhubii** [comment]
the requirements are resolved using `rosdep`:

```shell
rosdep install --from-paths src -i -r -y
```

I will try to explicitly state the ROS version, although it is already hinted at in the instructions, `source /opt/ros/humble/setup.bash`.

I agree that the OS is assumed to be Ubuntu. This should be fixed. Ideally, Windows support should be added here

**Comment by mhubii** [comment]
added individual build status in https://github.com/lbr-stack/lbr_fri_ros2_stack/pull/203
