### ISSUE TITLE
Trigger readthedocs build

### ISSUE THREAD

**Issue by mhubii** [lbr-stack/lbr_stack_doc#9]
Trigger readthedocs build through github actions

**Comment by CameronDevine** [comment]
readthedocs.io also has a built in GitHub integration (https://docs.readthedocs.io/en/stable/reference/git-integration.html).

While not required, I think this is a useful step, which I would prefer to see completed as part of the JOSS review (openjournals/joss-reviews#6138).

**Comment by mhubii** [comment]
webhook added, docs are now run on push
